### ISSUE TITLE
how to ?

### ISSUE THREAD

**Issue by gyeyoqu** [JaraLowell/OgarClient#10]
How to make if I have the name 'hello' my name will look another color in the leaderboard?

**Comment by JaraLowell** [comment]
How is it you host a web game and not know even the basics of the code you serve to your clients?

You could simply check what name is set, and then change the color to one you like. And can we stop opening new issues for something that is not an issue ?

**Comment by gyeyoqu** [comment]
i tried with if / else and not work

**Comment by gyeyoqu** [comment]
```
 if ( this.name == 'hello' ) {
                     ctx.fillStyle = me ? "#AAFFFF" : '#FFFAAA';;
                 
                } else {
                    ctx.fillStyle = me ? "#AAFFFF" : colors[i];
                 
                }
```

**Comment by gyeyoqu** [comment]
help me please

**Comment by JaraLowell** [comment]
More easy to add it to 
`if(msg.admin) { msg.name = "\uD83D\uDD75"; msg.nameColor = "#7D7D7D"; divider = " "; }`

like
`if(msg.name == 'hello') { msg.nameColor = "#FFFAAA"; }`

But that be things any JS coder should be able to figure out! 👿

**Comment by gyeyoqu** [comment]
lol :( i mean to the name in the leaderboard :(

**Comment by gyeyoqu** [comment]
is more hard :(

**Comment by makandz** [comment]
https://www.codecademy.com/learn/javascript

**Comment by gyeyoqu** [comment]
That course I already have it in 60% and it still does not work if / else, I also have functions, switch, operators and more, but I still can not do it

**Comment by gyeyoqu** [comment]
please help me

**Comment by JaraLowell** [comment]
`if (o == 'hello')`

**Comment by gyeyoqu** [comment]
@JaraLowell  rlly?

**Comment by JaraLowell** [comment]
not `this.name`, but `o`

**Comment by gyeyoqu** [comment]
lol , soo easy ? ;-;

**Comment by gyeyoqu** [comment]
And how can I do an 'if', if it is an admin, that works without writing in the chat

**Comment by JaraLowell** [comment]
You can't as leader board does not know how one is logged in.

**Comment by gyeyoqu** [comment]
nope, i mean to an if any, but with the condition that it is admin, not necessarily for the leaderboard, example in draw function:

if (window.admin) {

mainCtx.restore()
mainCtx.drawImage(image, x, y, size, isMass)

}

I did not know how to go to the variable, so I used it as a global variable XD

for example drawing an image from a URL if it is an administrator, this should work, but only works when I write in the chat, and I think this is by the chat handle


What I can do ?

**Comment by JaraLowell** [comment]
Again you would need to server side add or edit. As the client not knows one be  logged in as admin, most cheap way for you is send an msg over chat to let clients know but not write it to chat. Something like that, i my self not gone add this as i no need know when i am logged in as i know when i am ;3

**Comment by gyeyoqu** [comment]
the clients know with prefix of admin

**Comment by gyeyoqu** [comment]
0x40 for admin

**Comment by JaraLowell** [comment]
No it knows that the chatting person is an admin, it not knows if the 'name' is playing, nor whose cells belong to said name. As the server no tell this. As that would need to be the server telling this and it does not. Nor is that truly planned. So in that your in bad luck.

**Comment by gyeyoqu** [comment]
oh nice
