### ISSUE TITLE
Change QUALITY

### ISSUE THREAD

**Issue by gyeyoqu** [JaraLowell/OgarClient#13]
## 
The option to change the graphics only changes options such as edges, skins, etc, but really should be like agar.io in that the quality of the image changes, not the options

**Comment by JaraLowell** [comment]
Well that would mean you have to make multiple textures of one skin, like a 128x128 for lo quality in a lo folder, and going up to 1024x1024 for high; so lets say you do that go calculate your hd space needed for all skins you have active, as that be like 5x per skin. Hense why we not use it; and server side image tumbnalailing and rescalling is really no fun on the server tough possible... but still... yah a lot of work..

**Comment by gyeyoqu** [comment]
Nope, in c0nsume was implemented that, and it did not look so complicated and without server changes
