### ISSUE TITLE
PLEASE FIX!!!!!!!!!

### ISSUE THREAD

**Issue by gyeyoqu** [JaraLowell/OgarClient#15]
EMOTICOOOOONS

**Comment by JaraLowell** [comment]
?

**Comment by JaraLowell** [comment]
Please learn how to commit an issue, as what you posted there with no reference, examples or even an screen shot or explanation will get your request closed instantly.

**Comment by JaraLowell** [comment]
And Prot6 client works with emoticons

https://i.gyazo.com/f97a11d75911e416276b71c48ff8ad6b.png

**Comment by gyeyoqu** [comment]
nice

**Comment by gyeyoqu** [comment]
implement this pls

**Comment by JaraLowell** [comment]
it already is

**Comment by gyeyoqu** [comment]
ONLY WORK WITH OGARSERV ?

**Comment by JaraLowell** [comment]
eh yah?

**Comment by gyeyoqu** [comment]
not work with MultiOgar , says A buffer error

**Comment by JaraLowell** [comment]
We are OgarServ here,. not any other version 😈

**Comment by gyeyoqu** [comment]
I not know if ogarserv have good physics
