### ISSUE TITLE
Problem about trying show mass in LB

### ISSUE THREAD

**Issue by gyeyoqu** [JaraLowell/OgarClient#16]
I have tried to do the same method that is done in the cell, and put it in the leaderboard, but it has not worked for me

What could be simpler to draw the dough next to the name on the leaderboard?

`o = o.name + userScore;`

but show only my score
And the scores of the others, shows them with the amount of my score

how to show score 
independently

**Comment by JaraLowell** [comment]
Server Side Addon needed for that . . .

**Comment by gyeyoqu** [comment]
And to add positions without being inside the top 10?

**Comment by gyeyoqu** [comment]
Which file should you edit to display the scores next to the name on the leaderboard?

**Comment by JaraLowell** [comment]
One would have to adjust the leader board package js file, as well as the scoring in FFA js, making it not to go and count only the 15 or so people you see on lb; but to count all because you want to add more lag 👿
