### ISSUE TITLE
Only me

### ISSUE THREAD

**Issue by gyeyoqu** [JaraLowell/OgarClient#17]
For all the objects, for example I want to draw simply [CLAN] next to name, but they are drawn to all, as I do so that only ami is drawn, but all see? Any function

any property to only me?

**Comment by JaraLowell** [comment]
Server Side.... all things you keep asking is an fix slash add on you need to do server and client sided. Can't just do it from client, as the client has no clue what clan members all are playing, that be if we even had clan support. But allowing clans is saying, i allow teaming, and as players hate teaming, thus hating clans to.
