### ISSUE TITLE
Feature !!

### ISSUE THREAD

**Issue by RelTakeover** [JaraLowell/OgarClient#2]
Can you add a map where the others appear like alis.io ?

or a party system like gota.io ?

i think is easy for you , you are nice progammer =)

**Comment by makandz** [comment]
Others do appear on the map, right?

Why add a party system when you need to add the server first..

**Comment by JaraLowell** [comment]
Do not really see a party system be of that much use in a war game where it one man for all, even the so called clans battle each other when it comes down to it. Might be just me, now if you had a massive world map and an average of 100 people playing i can see it be of some use. Same as i do not like adding names to mini map, want to allow the small opportunity to least run a little, or hide if you are doing some from a large player. :3 it is why mini map stream has no names, also keeps the packages lo so we not stress the server to much.

**Comment by RelTakeover** [comment]
i have a server (ogar.pw) with Enough players,
Without taking into account that I am creator of agario.city

**Comment by RelTakeover** [comment]
pls help me

**Comment by JaraLowell** [comment]
You would need run OgarServ to utilize the mini map package, or ask the creator of the server you use to add it. So to once you have added that you would need read said package rather then forking in on the node data (p#16)

**Comment by RelTakeover** [comment]
i  want to use your server and your client, but could you create a party and map system like gota.io?

**Comment by RelTakeover** [comment]
I own an agar with more than 500 online, you can help me and advertise you?.

**Comment by makandz** [comment]
lol, I saw your 500 player thing on the tracker. I visited the server and I literally didn't see a single player other than bots 75% of the time.

**Comment by RelTakeover** [comment]
agario.city > ogartracker.tk

**Comment by SomeoneCares11** [comment]
I own servers with 1500 online without bots, help him and the voice reached😛

**Comment by JaraLowell** [comment]
OgarServ and client, combined has a working mini map system. It dues not reveal the name, because that be not needed on a mini map; nor is it updated every millisecond, but rather with the same frame as the leader board. This allows for some fair play and running away, sneaking about. The whole concept that makes it well cell wars. Party System on Agar.io was created to get people that joined a party in to the same server, or trying to. As Agar.io uses load balancing, spreading players out over multiple servers as they already seen and know, more then 50 players in an vanilla map, is simply to much 😈

**Comment by RelTakeover** [comment]
@JaraLowell  the people will can the people only in this party ! like gota.io

**Comment by makandz** [comment]
you are simply looking for things to improve your client by having others do it for you.

**Comment by SomeoneCares11** [comment]
@MastaCoder the improve for OgarClient not just his client, mine - yours - others

**Comment by makandz** [comment]
we don't need parties.

**Comment by SomeoneCares11** [comment]
@MastaCoder who do you mean by (we) ?

**Comment by makandz** [comment]
everyone.

**Comment by JaraLowell** [comment]
The extra needed server code and package adjusting, is not really worth adding it for the lo usage it would get. As in end that is what you need do, get a party code,. send it to server, server doe something with it or not and sends it back to clients. While obviously this might all be rather straight forwards, it would be bound to a select few of viewers only. As in end this is not an client only update.
