### ISSUE TITLE
MultiOgar Support

### ISSUE THREAD

**Issue by FlareYT** [JaraLowell/OgarClient#20]
Could you add a Feature that supports MultiOgar Games ?

Greetings Flare ! :)

**Comment by JaraLowell** [comment]
Or edit MultiOgar to support unicode :3 There a reason we walked away from it. Number one being, most our players use tablets and emoticons.

**Comment by FlareYT** [comment]
Well , would you help me to edit MultiOgar , so Unicodes get Supported ?

Greetings Flare ! :)

**Comment by JaraLowell** [comment]
Here i work on OgarServ and the client combined; it a whole package one can use. I am not really inclined to go and edit other servers or force them to follow my way. I should perhaps ask, why do you not use OgarServ, an server that works flawless with this client?
