### ISSUE TITLE
how to remove the black gradient in the center of a cell

### ISSUE THREAD

**Issue by happyhg3927** [JaraLowell/OgarClient#23]
![2017-03-03 21 44 16](https://cloud.githubusercontent.com/assets/13597009/23551622/fa2fa754-005a-11e7-956d-57692536b54d.PNG)

it looks like a black hole.

**Comment by JaraLowell** [comment]
Yah cells in Ogar client are translucent towards black.

**Comment by happyhg3927** [comment]
and then how can i change it?

**Comment by JaraLowell** [comment]
You would need to edit the js file and remove the gradients.

**Comment by happyhg3927** [comment]
Let me know what line I should change, please.

**Comment by JaraLowell** [comment]
1682: `mainCtx.fillStyle = settings.showColor ? fill : "#FFFFFF";`

could change that to `mainCtx.fillStyle = settings.showColor ? this.color : "#FFFFFF";`

But not something i add as i lovee the gradient look.

**Comment by happyhg3927** [comment]
thanks xD
