### ISSUE TITLE
Nodejs Problem

### ISSUE THREAD

**Issue by CAvciii** [JaraLowell/OgarClient#4]
![nodejs](https://cloud.githubusercontent.com/assets/25489592/22522322/d32b506c-e8c3-11e6-87aa-117b865af9d5.png)

Hello,

I want to install the multi ogar application. I see an error in the picture. What can I do?

**Comment by JaraLowell** [comment]
Why people keep asking about MultiOgar, while we here at OgarServ's repository ? Either case the error is actually quite straight forward, install node ( See https://nodejs.org/en/download/package-manager )

**Comment by CAvciii** [comment]
Who can ask for Multiogar? I have installed NodeJs on my server. But I see the error in the screen image. :) @JaraLowell

**Comment by JaraLowell** [comment]
Well as your error states, you do not have nodejs installed, check by doing `node -v` and if your `server` is windows 10 and then using Debian shell... you will get that to, installing node on windows, does not mean you have access to it in the shell. However if it is windows 10, you also have node shell.
