### ISSUE TITLE
emoticons

### ISSUE THREAD

**Issue by gyeyoqu** [JaraLowell/OgarClient#5]
emoticons not allow , as 💞

**Comment by JaraLowell** [comment]
Thats because protocol 6 and up do not allow emoticons in name as Protocol 5 and bellow did. So that is some ting to think about,. Protocol 6 and up is UTF8 while 5 and below is Unicode.

**Comment by gyeyoqu** [comment]
And what can be done ? Luka967 said he would fix it

**Comment by JaraLowell** [comment]
It needs both Server and Client fix, while this Port 6 client can do it (as for example chat is back to Unicode) We would have to do the same for Nick Names. While that is technically not that hard, if we state '6' is now new for web clients. And 7 and up for agar.io. However know that you then be stuck with 'OgarServ' and 'OgarClient' till other server and cigar also adjusts towards this.

**Comment by gyeyoqu** [comment]
you will fix?

**Comment by JaraLowell** [comment]
Working on it, making it that if protocol 6 expletive is used like with our prot6 client, that send it as Unicode rather then none unicode only. However this means if any other client using the protocol 6, will need send 7, 8, 9 or 10 as handshake to work. This is also a fix that needs an OgarServ update. Will commit this when i am done frilling around with it.

**Comment by JaraLowell** [comment]
Think i have the test client and server working with this idea; you can give it a try over at http://ogar.mivabe.nl/prot6 will get files on git tomorrow as it late for me here now.

**Comment by gyeyoqu** [comment]
LOL , is sooo buggy

**Comment by JaraLowell** [comment]
Crying about that some thing does not work does not really help in looking in to it to fix it. So a bit more then, 'it is buggy' be needed. So to need make sure you have the latest client version active, or it wont work either obviously.
