### ISSUE TITLE
party sistem

### ISSUE THREAD

**Issue by gyeyoqu** [JaraLowell/OgarClient#8]
like ugar.pw

**Comment by JaraLowell** [comment]
As i do not support teaming why would i thus add a party system ? Plus a party system only and truly make sense if you use load balancing of servers so you can get on same server as your friends. Moment you not use that and basicly all be on same server from get go it be pointless to have as it adds noting to the game.

**Comment by gyeyoqu** [comment]
I notice that you know too much, can you help me with my agar? Has enough people and I use protocol 6, is ogar.pw, some form of contact, many thanks
